copy /y "%XEngine_Lib64%\XEngine_BaseLib\XEngine_BaseLib.dll" "./"
copy /y "%XEngine_Lib64%\XEngine_BaseLib\XEngine_Algorithm.dll" "./"
copy /y "%XEngine_Lib64%\XEngine_Core\XEngine_OPenSsl.dll" "./"
copy /y "%XEngine_Lib64%\XEngine_SystemSdk\XEngine_SystemApi.dll" "./"
copy /y "%XEngine_Lib64%\XEngine_NetHelp\NetHelp_APIClient.dll" "./"

copy /y "%XEngine_Lib64%\XEngine_HelpComponents\zlib1.dll" "./"
copy /y "%XEngine_Lib64%\XEngine_LibEx\libcrypto-3-x64.dll" "./"
copy /y "%XEngine_Lib64%\XEngine_LibEx\libssl-3-x64.dll" "./"
copy /y "%XEngine_Lib64%\XEngine_NetHelp\libcurl.dll" "./"
copy /y "%XEngine_Lib64%\XEngine_NetHelp\nghttp2.dll" "./"