#pragma once

#define XENGINE_STORAGE_APP_METHOD_ADD _T("Add")
#define XENGINE_STORAGE_APP_METHOD_DEL _T("Del")
#define XENGINE_STORAGE_APP_METHOD_QUERYFILE _T("Query")
#define XENGINE_STORAGE_APP_METHOD_TASK _T("Task")
#define XENGINE_STORAGE_APP_METHOD_DIR _T("Dir")
#define XENGINE_STORAGE_APP_METHOD_LAN _T("Lan")
#define XENGINE_STORAGE_APP_METHOD_QUERY _T("Query")

BOOL XEngine_Task_Manage(LPCTSTR lpszAPIName, LPCTSTR lpszClientAddr, LPCTSTR lpszMsgBuffer, int nMsgLen, RFCCOMPONENTS_HTTP_REQPARAM* pSt_HTTPParam, TCHAR** pptszListHdr, int nHdrCount);